_site_home:
    resource: "@MinCommerceSiteBundle/Controller/HomeController.php"
    type:     annotation
    prefix:   /

_site_categories:
    resource: "@MinCommerceSiteBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /cat

_site_products:
    resource: "@MinCommerceSiteBundle/Controller/ProductController.php"
    type:     annotation
